# Generated by Django 4.2.5 on 2024-02-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_movie_description_remove_movie_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.TextField(default='Unknown', max_length=255),
        ),
    ]
