# Generated by Django 4.2.5 on 2024-02-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='item_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
