# Generated by Django 4.2.5 on 2024-02-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_movie_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='item_id',
            field=models.CharField(default='1', max_length=50, unique=True),
        ),
    ]
