# Generated by Django 4.2.5 on 2024-02-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_movie_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='item_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
